name: Aggiornamento AI Previsioni

on:
  schedule:
    - cron: "*/90 * * * *"  # ogni 90 minuti
  workflow_dispatch:        # esecuzione manuale dal tab Actions

jobs:
  update-signals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Esegui script AI
        run: node update-signals.js

      - name: Commit e Push del nuovo previsioni.json
        run: |
          git config user.name "AI Bot"
          git config user.email "ai-bot@users.noreply.github.com"
          git add previsioni.json
          git commit -m "🤖 Aggiornamento automatico previsioni AI"
          git push